version: '3'
services:

    redis:
        container_name: redis
        image: redis
        hostname: redis
#        command: redis-server --requirepass password
        restart: always
        ports:
            - 6379:6379
    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 8081:8081
    database:
        container_name: postgresql
        image: postgres
        ports:
            - 5434:5432
        env_file:
            - database.env
        restart: always

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
