cbr:
  uri: 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx'
  wsdl:
    GenerationPackage: 'ru.proskuryakov.cbrcursondateadapter.cbr.wsdl'

cache:
  SaveTime: 60

#logging:
#  level:
#    org:
#      springframework:
#        ws:
#          client:
#            MessageTracing:
#              sent: TRACE
#              received: TRACE
