cbr:
  uri: 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx'
  wsdl:
    GenerationPackage: 'ru.proskuryakov.cbrcursondateadapter.cbr.wsdl'

logging:
  level:
    org:
      springframework:
        ws:
          client:
            MessageTracing:
              sent: TRACE
              received: TRACE
