cbr:
  uri: 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx'
  wsdl:
    GenerationPackage: 'ru.proskuryakov.cbrcursondateadapter.cbr.wsdl'

redis:
  ttl: 5 # minutes

spring:
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: password
  datasource:
    url: jdbc:postgresql://localhost:5434/curs-history
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

scheduler:
  fixedDelay: 60000 #seconds
  initialDelay: 1000 #seconds

#logging:
#  level:
#    org:
#      springframework:
#        ws:
#          client:
#            MessageTracing:
#              sent: TRACE
#              received: TRACE
