cbr:
  uri: 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx'
  wsdl:
    GenerationPackage: 'ru.proskuryakov.cbrcursondateadapter.cbr.wsdl'

redis:
  ttl: 5 # minutes

spring:
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: password


#logging:
#  level:
#    org:
#      springframework:
#        ws:
#          client:
#            MessageTracing:
#              sent: TRACE
#              received: TRACE
