cbr:
  uri: 'http://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx'
  wsdl:
    GenerationPackage: 'ru.proskuryakov.cbrcursondateadapter.cbr.wsdl'

redis:
  ttl: 5 # minutes

spring:
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: password
  datasource:
    url: jdbc:postgresql://localhost:5434/curs-history
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true

scheduler:
  fixedDelay: 60000 #seconds
  initialDelay: 1000 #seconds
  interval-coefficient: 1000

rabbitmq:
  exchange:
    history: change-history-exchange
    logging: logging-exchange
  routingkey:
    history: change-history-routingkey
    logging: logging-routingkey
  queue:
    history: change-history-queue
    logging: logging-queue


#logging:
#  level:
#    org:
#      springframework:
#        ws:
#          client:
#            MessageTracing:
#              sent: TRACE
#              received: TRACE
